sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Bz+tdKBgZR8aZFge3MNHjV1F/4m5KxFOAfvAdpTnAnfo6imhKrruWTuoO/RzUY7TrExJ4GHAZz8owes+PUWjfv/xVwEtfZrpoLNm8qYobc+kw6bo2E6mKe70u3g9rG9/Wu4B4MYf7KiqZ90P9SfhZaUawl/fLh6HFCBXh3/ucs8FRy4CQubzzSGJU91Zwd/Ial+b8FYIeru5UyWmZktjvCT/uF9aFyRIOW/pGmsotYKcjfk91PDDch3ariOAoAxUWXv0BOtVLSpoczOHp7lp40cmhdhjzvTneCGcFoKjcxgyfKvpniWfnFtgVDG1ktjG8DoBtDQgg+lp6ZQka1pyJlojjN1h9I6k5sl83LFCPINHBHnA+Q3iTog4V8nkJy9OSEFsiGPxW3FHItmhpZRTIniWnxP8HyidJicHCVrJrm+vTlTnxqLlSG+q22IwFckyYTS3fOc47T7DnhezpDkJa2eFEeMwopFbKhTB9e+S1kA2Y1AlofGzLZ0MFCl/6eCG0iy6C5NPki6pt+4i9pU/wP/bSDmcxF+P3VxOa6sHSg4uDi/cyp1EdsKNzGTuiDJcFHecjMQRuvqNNCNajjwMyh8ies7Juf4u2goXqm9ryuQs7wvMpJ79bBK4C5vC6C6eRaSdkugqi1MYjomGPc8OeulT1Lrjz4PHjfWpX7C1MQs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Polly-of-the-Circus_859
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy